# Generated by Django 5.1.7 on 2025-06-23 10:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_time', models.DateTimeField(auto_now_add=True)),
                ('honey_used', models.PositiveIntegerField(default=2700)),
                ('is_successful', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(blank=True, default='default_images/default.png', null=True, upload_to='profile_images/')),
                ('honey_count', models.IntegerField(default=0)),
                ('completed_todo_count', models.IntegerField(default=0)),
                ('daily_honey_earned', models.IntegerField(default=0)),
                ('last_honey_earned_date', models.DateField(blank=True, null=True)),
                ('total_study_time', models.DurationField(default=datetime.timedelta)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('followings', models.ManyToManyField(related_name='followers', to='accounts.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
