# Generated by Django 5.1.7 on 2025-06-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_daily_honey_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_honey_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_honey_earned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DailyHoney',
        ),
    ]
