# Generated by Django 5.2.3 on 2025-06-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='honey_codunt',
            new_name='honey_count',
        ),
    ]
