# Generated by Django 5.1.7 on 2025-06-24 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_daily_honey_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_study_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
