# Generated by Django 5.2.3 on 2025-06-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_honey_codunt_profile_honey_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
