# Generated by Django 5.2.3 on 2025-06-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_followings'),
        ('accounts', '0005_alter_profile_profile_image'),
    ]

    operations = [
    ]
