# Generated by Django 5.2.3 on 2025-06-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_honey_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_honey_earned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
