# Generated by Django 5.2.3 on 2025-06-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20250620_2039'),
        ('accounts', '0006_profile_daily_honey_earned_and_more'),
    ]

    operations = [
    ]
