# Generated by Django 5.2.3 on 2025-06-23 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_giftexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_study_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
