# Generated by Django 5.1.7 on 2025-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ended_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='started_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
