# Generated by Django 5.2.3 on 2025-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_todo_ended_at_alter_todo_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('대외활동', '대외활동'), ('과제', '과제'), ('시험공부', '시험공부'), ('자격증', '자격증'), ('알바', '알바'), ('동아리', '동아리'), ('취미활동', '취미활동'), ('기타', '기타')], max_length=20),
        ),
    ]
