# Generated by Django 5.1.7 on 2025-06-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_todo_date_todo_total_elapsed_time_dailygoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
