# Generated by Django 5.1.7 on 2025-06-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='todo',
        ),
    ]
