# Generated by Django 5.1.7 on 2025-06-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_comment_user_alter_comment_date_alter_comment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
