# Generated by Django 5.1.7 on 2025-06-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_comment_user'),
        ('planner', '0011_alter_todo_started_at'),
    ]

    operations = [
    ]
