# Generated by Django 5.2.1 on 2025-06-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_merge_20250622_1306'),
        ('planner', '0013_alter_comment_user'),
    ]

    operations = [
    ]
