# Generated by Django 5.1.7 on 2025-06-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_merge_20250622_1651'),
        ('planner', '0014_merge_20250622_1707'),
    ]

    operations = [
    ]
