# Generated by Django 5.2.3 on 2025-06-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_merge_20250622_1254'),
        ('planner', '0015_like'),
        ('planner', '0016_like'),
    ]

    operations = [
    ]
